// 026. Desarrolla una aplicación con Spring Boot y Vue.js/spring-vue/frontend/src/components/EmployeeList.vue
<template>

  <div class="container text-center">
    <div class="row">
      <div class="col-2">

      </div>
      <div class="col-8">
        <h2>Employee List</h2>
        <ul class="list-group">
          <li class="list-group-item"
              v-for="(employee, index) in employees" :key="index">
            {{employee.id}} - {{employee.name}} - {{employee.role}}
          </li>
        </ul>

        <table class="table">
          <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Role</th>
          </tr>
          </thead>
          <tbody>
          <tr v-for="(employee, index) in employees" :key="index">
            <th scope="row">{{employee.id}}</th>
            <td>{{employee.name}}</td>
            <td>{{employee.role}}</td>
          </tr>
          </tbody>
        </table>


      </div>


      <div class="col-2">

      </div>
    </div>
  </div>

  <router-view></router-view>
</template>

<script>
import EmployeeService from '@/services/EmployeeService';
export default {
  name: "EmployeeList",
  data() {
    return {
      employees: []
    }
  },
  methods: {
    fetchEmployees() {
      EmployeeService.findAll().then(response => {
        this.employees = response.data;
        console.log(response.data);
      }).catch(error => {console.log(error)});
    }

  },
  mounted(){
    this.fetchEmployees();
  }
}
</script>

<style scoped>

</style>

// 025. Desarrolla una aplicación con Spring Boot y React/spring-react/frontend/src/components/EmployeeList.js
import React, {useEffect, useState} from 'react';
import axios from 'axios';
import {Link, useNative} from 'react-router-dom'

const EmployeeList = () => {

    const baseUrl = "http://localhost:8080/api/employees";
    const [employees, setEmployees] = useState([])

    const fetchEmployees = () => {
        axios.get(baseUrl).then(response => {
            console.log(response.data);
            setEmployees(response.data);
        }).catch(error => {
            console.log('Error fetching employee data ' + error);
        })
    }

    useEffect(() => {
        fetchEmployees()
    }, [])

    function removeEmployee(id) {
        console.log("Removing employee " + id)
    }

    return (
        <div className="container text-center">
            <div className="row">
                <div className="col">

                </div>
                <div className="col">

                    <table className="table">
                        <thead>
                        <tr>
                            <th scope="col">Id</th>
                            <th scope="col">Name</th>
                            <th scope="col">Role</th>
                            <th scope="col">Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        { employees && employees.map(employee => (
                            <tr>
                                <th scope="row">{employee.id}</th>
                                <td>{employee.name}</td>
                                <td>{employee.role}</td>
                                <td>
                                    <Link className="btn btn-success" to={"/edit/" + employee.id}>Editar</Link>
                                    <button className="btn btn-danger" onClick={() => removeEmployee(employee.id)}>Borrar</button>
                                </td>
                            </tr>
                        ))
                        }


                        </tbody>
                    </table>


                </div>
                <div className="col">

                </div>
            </div>
        </div>
    );

}
export default EmployeeList
